/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Conexao;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Henrique
 */
public class TabelaPacientes extends javax.swing.JDialog {

    private Conexao c;    
    public TabelaPacientes() {
        initComponents();
        this.setModal(true);
        this.c = new Conexao();  
        this.setDados();
    }

    private void setDados() {
        DefaultTableModel d = (DefaultTableModel) grdPacientes.getModel();
        
        //Deletar linhas
        while(d.getRowCount() > 0) {
            d.removeRow(0);
        }          
        
        try {
            this.c.setResultSet("SELECT * FROM paciente");
            if (this.c.getResultSet().first()) {
                do {
                    Object[] Linha = {
                        this.c.getResultSet().getString("CodPaciente"),
                        this.c.getResultSet().getString("Nome"),
                        this.c.getResultSet().getString("Cpf"),
                        this.c.getResultSet().getString("Altura"),
                        this.c.getResultSet().getString("Peso"),
                    };
                    d.addRow(Linha);
                } while(this.c.getResultSet().next());
            }
        }
        catch(SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    private boolean IsLinhaSelecionada() {
        if (grdPacientes.getRowCount() < 1) {
            JOptionPane.showMessageDialog(this, "O cadastro não possui registros");
            return false;
        } 
        else if (grdPacientes.getSelectedRowCount() < 1) {
            JOptionPane.showMessageDialog(this, "Selecionar um aluno");
            return false;
        }
        else
            return true;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        grdPacientes = new javax.swing.JTable();
        Button_Cadastrar = new javax.swing.JButton();
        Button_Editar = new javax.swing.JButton();
        Button_Excluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        grdPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo Paciente", "Nome", "CPF", "Altura", "Peso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(grdPacientes);

        Button_Cadastrar.setText("Cadastrar");
        Button_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CadastrarActionPerformed(evt);
            }
        });

        Button_Editar.setText("Editar");
        Button_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EditarActionPerformed(evt);
            }
        });

        Button_Excluir.setText("Excluir");
        Button_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Button_Cadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Excluir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Cadastrar)
                    .addComponent(Button_Editar)
                    .addComponent(Button_Excluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CadastrarActionPerformed
        // TODO add your handling code here:
        new EntradaPacientes("0").setVisible(true);
        this.setDados();
    }//GEN-LAST:event_Button_CadastrarActionPerformed

    private void Button_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ExcluirActionPerformed
        // TODO add your handling code here:  
        if (IsLinhaSelecionada()) {
            int e = JOptionPane.showConfirmDialog(this, 
                    "Deseja realmente excluir o registro selecionado?", 
                    "Confirmar exclusão", 
                    JOptionPane.YES_NO_OPTION);

            if (e == JOptionPane.YES_OPTION) {
                String cod = grdPacientes.getValueAt(grdPacientes.getSelectedRow(), 0).toString();
                this.c.SQLExecute("DELETE FROM paciente WHERE CodPaciente = " + cod);
                JOptionPane.showMessageDialog(this, "Registro excluído com sucesso");
                this.setDados();
            }
        }                             
    }//GEN-LAST:event_Button_ExcluirActionPerformed

    private void Button_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EditarActionPerformed
        // TODO add your handling code here:
        if (IsLinhaSelecionada()) {
            String m = grdPacientes.getValueAt(grdPacientes.getSelectedRow(), 0).toString();
            new EntradaPacientes(m).setVisible(true);
            this.setDados(); 
        }
    }//GEN-LAST:event_Button_EditarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Cadastrar;
    private javax.swing.JButton Button_Editar;
    private javax.swing.JButton Button_Excluir;
    private javax.swing.JTable grdPacientes;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
